# Generated by Django 3.0.5 on 2020-04-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFiles', '0002_auto_20200421_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='subject',
        ),
    ]
