# Generated by Django 3.0.5 on 2020-04-21 08:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uploadFiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isprivate', models.BooleanField(default=True)),
                ('filename', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=uploadFiles.models.user_directory_path)),
                ('give_access_to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('year', models.IntegerField(blank=True)),
                ('semister', models.IntegerField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('lecturer_name', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
