# Generated by Django 3.0.5 on 2020-04-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFiles', '0003_auto_20200423_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='isprivate',
        ),
    ]
